name: Continuous integration

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - python-version: 3.6
            os: ubuntu-latest
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pygraph and sndfile
      run: |
        sudo apt-get install python-pygraph python-pygraphviz
        sudo apt-get install libsndfile1
    - name: Upgrade pip and install requirements and SymJAX
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: Run tests
      run: pytest


